/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewServiceRequest = IDL.Record({
  'vehicleType' : IDL.Text,
  'tyreType' : IDL.Text,
  'issue' : IDL.Text,
  'location' : IDL.Text,
});
export const DealerProfile = IDL.Record({
  'id' : IDL.Principal,
  'totalRatings' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'vehicleType' : IDL.Text,
  'createdAt' : IDL.Int,
  'customerRating' : IDL.Opt(IDL.Nat),
  'updatedAt' : IDL.Int,
  'tyreType' : IDL.Text,
  'customerId' : IDL.Principal,
  'issue' : IDL.Text,
  'location' : IDL.Text,
  'dealerId' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRequest' : IDL.Func([IDL.Text], [], []),
  'completeRequest' : IDL.Func([IDL.Text], [], []),
  'createServiceRequest' : IDL.Func([NewServiceRequest], [IDL.Text], []),
  'getActiveDealers' : IDL.Func([], [IDL.Vec(DealerProfile)], ['query']),
  'getAllDealers' : IDL.Func([], [IDL.Vec(DealerProfile)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getDealerProfile' : IDL.Func([IDL.Principal], [DealerProfile], ['query']),
  'getDealerRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getOpenRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getPendingRequestsByDealer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getRequestsByDealer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getServiceRequest' : IDL.Func([IDL.Text], [ServiceRequest], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateDealer' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'registerDealer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewServiceRequest = IDL.Record({
    'vehicleType' : IDL.Text,
    'tyreType' : IDL.Text,
    'issue' : IDL.Text,
    'location' : IDL.Text,
  });
  const DealerProfile = IDL.Record({
    'id' : IDL.Principal,
    'totalRatings' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'vehicleType' : IDL.Text,
    'createdAt' : IDL.Int,
    'customerRating' : IDL.Opt(IDL.Nat),
    'updatedAt' : IDL.Int,
    'tyreType' : IDL.Text,
    'customerId' : IDL.Principal,
    'issue' : IDL.Text,
    'location' : IDL.Text,
    'dealerId' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRequest' : IDL.Func([IDL.Text], [], []),
    'completeRequest' : IDL.Func([IDL.Text], [], []),
    'createServiceRequest' : IDL.Func([NewServiceRequest], [IDL.Text], []),
    'getActiveDealers' : IDL.Func([], [IDL.Vec(DealerProfile)], ['query']),
    'getAllDealers' : IDL.Func([], [IDL.Vec(DealerProfile)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getDealerProfile' : IDL.Func([IDL.Principal], [DealerProfile], ['query']),
    'getDealerRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getOpenRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getPendingRequestsByDealer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getRequestsByDealer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getServiceRequest' : IDL.Func([IDL.Text], [ServiceRequest], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateDealer' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'registerDealer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };