/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DealerProfile {
  'id' : Principal,
  'totalRatings' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'address' : string,
  'rating' : number,
  'phone' : string,
}
export interface NewServiceRequest {
  'vehicleType' : string,
  'tyreType' : string,
  'issue' : string,
  'location' : string,
}
export interface ServiceRequest {
  'id' : string,
  'status' : string,
  'vehicleType' : string,
  'createdAt' : bigint,
  'customerRating' : [] | [bigint],
  'updatedAt' : bigint,
  'tyreType' : string,
  'customerId' : Principal,
  'issue' : string,
  'location' : string,
  'dealerId' : [] | [Principal],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRequest' : ActorMethod<[string], undefined>,
  'completeRequest' : ActorMethod<[string], undefined>,
  'createServiceRequest' : ActorMethod<[NewServiceRequest], string>,
  'getActiveDealers' : ActorMethod<[], Array<DealerProfile>>,
  'getAllDealers' : ActorMethod<[], Array<DealerProfile>>,
  'getAllRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getDealerProfile' : ActorMethod<[Principal], DealerProfile>,
  'getDealerRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getOpenRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getPendingRequestsByDealer' : ActorMethod<
    [Principal],
    Array<ServiceRequest>
  >,
  'getRequestsByDealer' : ActorMethod<[Principal], Array<ServiceRequest>>,
  'getServiceRequest' : ActorMethod<[string], ServiceRequest>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rateDealer' : ActorMethod<[string, bigint], undefined>,
  'registerDealer' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];